name: Auto Commit and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Commit and Push
      run: |
        git config --global user.email "nitinya9av@gmail.com"
        git config --global user.name "Nitin Yadav"
        git add .
        git commit -m "$(date +'%A %d-%m-%Y %H:%M:%S %Z')"
        git push
