name: Auto Commit

on:
  schedule:
    - cron: '*/5 * * * *'  # This will run every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add & Commit
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'Nitin Yadav'
        author_email: 'nitinya9av@gmail.com'
        message: "$(date +'%A %d-%m-%Y %H:%M:%S %Z')"
        add: '.'